# -*- coding: utf-8 -*-
"""Deep_Gradient_Decent_Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mwqG2OGrTG7RV59uyr9qMeTIBQNj3wYp
"""

import pandas as pd
import numpy as np
import seaborn as sns

df = pd.read_csv('fake_reg.csv')

df.head()

sns.pairplot(df)

from sklearn.model_selection import train_test_split

X = df[['feature1', 'feature2']].values
y = df['price'].values

X

y

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

X_train.shape

X_test.shape

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaler.fit(X_train)

X_train = scaler.transform(X_train)

X_test =  scaler.transform(X_test)

X_train.min()

X_train.max()

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([Dense(65, activation='relu'),
                    Dense(60, activation='relu' ),
                    Dense(55, activation='relu'), 
                    Dense(50, activation='relu'),
                    Dense(45, activation='relu'),
                    Dense(40, activation='relu'),
                    Dense(35, activation='relu'),
                    Dense(30, activation='relu'),
                    Dense(25, activation='relu'),
                    Dense(20, activation='relu'),
                    Dense(15, activation='relu'),\
                    Dense(10, activation='relu'),
                    Dense(5, activation='relu'),
                    Dense(1)])

model.compile(optimizer='rmsprop', loss='mse')

model.fit(x=X_train, y=y_train, epochs=250)

loss_df = pd.DataFrame(model.history.history)
 loss_df.plot()

model.evaluate(X_test, y_test, verbose=0)

model.evaluate(X_train, y_train, verbose=0)

!pip install h5py pyyaml

model.summary()

model.save('basic_deep_regression.h5')

from keras.models import load_model
new_model = load_model('basic_deep_regression.h5')

new_model.summary()

json_string = model.to_json()

json_string

